In [1]:
import  pandas as pd 
import numpy  as np

In [2]:
df = pd.read_csv('myrgroup.csv') 
df

        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [3]:
def cybrom (n) : 
    if n>8 :
        return n

In [5]:
cybrom(10)

10

In [6]:
df['windspeed'].apply(cybrom)

0    10.0
1     NaN
2    18.0
3    16.0
4     NaN
5    20.0
6     NaN
7    17.0
8     NaN
Name: windspeed, dtype: float64

In [7]:
df['windspeed'] = df['windspeed'].fillna(0) 
df['windspeed'] = df['windspeed'].astype(int) 
df.apply(min)

day          1/1/2024
city           bhopal
weather           fog
temp             19.0
windspeed           0
dtype: object

In [8]:
df['temp'].apply(lambda x:x+10)

0    34.0
1    42.0
2    30.0
3    30.0
4    45.0
5    31.0
6    48.0
7    29.0
8     NaN
Name: temp, dtype: float64

In [9]:
df.agg({'temp':'sum','windspeed':'max'})

temp         209.0
windspeed     20.0
dtype: float64

In [10]:
df.agg(['min','max','sum','count'])

,day,city,weather,temp,windspeed
min,1/1/2024,bhopal,fog,19.0,0
max,1/9/2024,ujjain,sunny,38.0,20
sum,1/1/20241/2/20241/3/20241/4/20241/5/20241/6/20...,bhopalindorebhopalbhopalindorebhopalujjainujja...,fogsunnyrainyfogsunnyrainysunnyrainyfog,209.0,93
count,9,9,9,8.0,9

In [11]:
df.agg(['min','max','count'])

            day    city weather  temp  windspeed
min    1/1/2024  bhopal     fog  19.0          0
max    1/9/2024  ujjain   sunny  38.0         20
count         9       9       9   8.0          9

In [12]:
c = df.groupby('city') 
for k,v in c: 
    print(k) 
    print(v)

bhopal
        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0         10
2  1/3/2024  bhopal   rainy  20.0         18
3  1/4/2024  bhopal     fog  20.0         16
5  1/6/2024  bhopal   rainy  21.0         20
indore
        day    city weather  temp  windspeed
1  1/2/2024  indore   sunny  32.0          4
4  1/5/2024  indore   sunny  35.0          5
ujjain
        day    city weather  temp  windspeed
6  1/7/2024  ujjain   sunny  38.0          3
7  1/8/2024  ujjain   rainy  19.0         17
8  1/9/2024  ujjain     fog   NaN          0

In [17]:
c1=df.groupby('weather') 
for s,v in c1:
    print(s) 
    print(v)

fog
        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0         10
3  1/4/2024  bhopal     fog  20.0         16
8  1/9/2024  ujjain     fog   NaN          0
rainy
        day    city weather  temp  windspeed
2  1/3/2024  bhopal   rainy  20.0         18
5  1/6/2024  bhopal   rainy  21.0         20
7  1/8/2024  ujjain   rainy  19.0         17
sunny
        day    city weather  temp  windspeed
1  1/2/2024  indore   sunny  32.0          4
4  1/5/2024  indore   sunny  35.0          5
6  1/7/2024  ujjain   sunny  38.0          3

In [21]:
c.get_group('ujjain')

        day    city weather  temp  windspeed
6  1/7/2024  ujjain   sunny  38.0          3
7  1/8/2024  ujjain   rainy  19.0         17
8  1/9/2024  ujjain     fog   NaN          0

In [22]:
df[df['city'].isin(['ujjain','indore'])]

        day    city weather  temp  windspeed
1  1/2/2024  indore   sunny  32.0          4
4  1/5/2024  indore   sunny  35.0          5
6  1/7/2024  ujjain   sunny  38.0          3
7  1/8/2024  ujjain   rainy  19.0         17
8  1/9/2024  ujjain     fog   NaN          0

In [23]:
df[~df['city'].isin(['bhopal','ujjain'])]

        day    city weather  temp  windspeed
1  1/2/2024  indore   sunny  32.0          4
4  1/5/2024  indore   sunny  35.0          5