In [1]:
import pandas as pd 
import numpy as np

In [3]:
l = [1,2,3,4,5,6,7] 
df = pd.DataFrame(l) 
df

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [4]:
l = [[1,2,3,4,5],[10,20,30,40,50,60]] 
df = pd.DataFrame(l) 
df

    0   1   2   3   4     5
0   1   2   3   4   5   NaN
1  10  20  30  40  50  60.0

In [6]:
l = [[1,2,3,4,5],[10,20,30,40,50,60]] 
df = pd.DataFrame(l,columns=['mon','tue','wed','thur','fri','sat']) 
df

   mon  tue  wed  thur  fri   sat
0    1    2    3     4    5   NaN
1   10   20   30    40   50  60.0

In [7]:
t = (1,2,3,4,5) 
df = pd.DataFrame(t) 
df

   0
0  1
1  2
2  3
3  4
4  5

In [10]:
d = {'x':[1],'y':[2],'z':[3]} 
print(type(d))
df = pd.DataFrame(d)
print(df.columns)
print(df.index)
print(df.values)

<class 'dict'>
Index(['x', 'y', 'z'], dtype='str')
RangeIndex(start=0, stop=1, step=1)
[[1 2 3]]

In [14]:
d = pd.read_csv('sample_submission.csv')
df = pd.DataFrame(d) 
df

           City StationId        Date AQI_Bucket
0     Amaravati     AP001  2020-01-01   Moderate
1     Amaravati     AP001  2020-01-02   Moderate
2     Amaravati     AP001  2020-01-03   Moderate
3     Amaravati     AP001  2020-01-04   Moderate
4     Amaravati     AP001  2020-01-05   Moderate
...         ...       ...         ...        ...
2988    Kolkata     WB013  2020-06-25   Moderate
2989    Kolkata     WB013  2020-06-26   Moderate
2990    Kolkata     WB013  2020-06-29   Moderate
2991    Kolkata     WB013  2020-06-30   Moderate
2992    Kolkata     WB013  2020-07-01   Moderate

[2993 rows x 4 columns]

In [16]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [21]:
d = pd.read_excel('StudentPerformanceFactors.xlsx',usecols=[0,5] , nrows=5) 
df = pd.DataFrame(d) 
df

   Hours_Studied  Sleep_Hours
0             23            7
1             19            8
2             24            7
3             29            8
4             19            6

## attribute :

# shape :

In [3]:
# shape : 
d = pd.read_excel('StudentPerformanceFactors.xlsx',usecols=[0,5] , nrows=5) 
df = pd.DataFrame(d) 
df.shape
print(df.dtypes)

Hours_Studied    int64
Sleep_Hours      int64
dtype: object

In [36]:
l = [[10,2,30,4,5],[10,20,30,40,50,60],[10,20,30,40,50,60]] 
df = pd.DataFrame(l,columns=['mon','tue','wed','thur','fri','sat']) 
df.shape
print(df.index)
print(df.values)
print(df.dtypes)
print(df.columns)
print(df.isnull())
print(df.isnull().sum()) 
print(df.notnull())  
print(df.duplicated()) 
print(df.duplicated().sum())

RangeIndex(start=0, stop=3, step=1)
[[10.  2. 30.  4.  5. nan]
 [10. 20. 30. 40. 50. 60.]
 [10. 20. 30. 40. 50. 60.]]
mon       int64
tue       int64
wed       int64
thur      int64
fri       int64
sat     float64
dtype: object
Index(['mon', 'tue', 'wed', 'thur', 'fri', 'sat'], dtype='str')
     mon    tue    wed   thur    fri    sat
0  False  False  False  False  False   True
1  False  False  False  False  False  False
2  False  False  False  False  False  False
mon     0
tue     0
wed     0
thur    0
fri     0
sat     1
dtype: int64
    mon   tue   wed  thur   fri    sat
0  True  True  True  True  True  False
1  True  True  True  True  True   True
2  True  True  True  True  True   True
0    False
1    False
2     True
dtype: bool
1

In [28]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
df .shape

(6607, 20)

# dtype:

In [27]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
print(df.dtypes)

Hours_Studied                   int64
Attendance                      int64
Parental_Involvement              str
Access_to_Resources               str
Extracurricular_Activities        str
Sleep_Hours                   float64
Previous_Scores                 int64
Motivation_Level                  str
Internet_Access                   str
Tutoring_Sessions             float64
Family_Income                     str
Teacher_Quality                   str
School_Type                       str
Peer_Influence                    str
Physical_Activity               int64
Learning_Disabilities             str
Parental_Education_Level          str
Distance_from_Home                str
Gender                            str
Exam_Score                      int64
dtype: object

In [29]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='str')

In [7]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
print(df.index)
print(df.values)

RangeIndex(start=0, stop=6607, step=1)
[[23 84 'Low' ... 'Near' 'Male' 67]
 [19 64 'Low' ... 'Moderate' 'Female' 61]
 [24 98 'Medium' ... 'Near' 'Male' 74]
 ...
 [20 90 'Medium' ... 'Near' 'Female' 68]
 [10 86 'High' ... 'Far' 'Female' 68]
 [15 67 'Medium' ... 'Near' 'Male' 64]]

In [33]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
df.info()  # info is a function

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6594 non-null   float64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6604 non-null   float64
 10  Family_Income               6607 non-null   str
 11  Teacher_Quality             6529 non-null   str
 12  School_Type                 6607 non-null   str
 13  Peer_Influence              6607 non-null   str
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   str
 16  Parental_Education_Level    6517 non-null   str
 17  Distance_from_Home          6540 non-null   str
 18  Gender                      6607 non-null   str
 19  Exam_Score                  6607 non-null   int64
dtypes: float64(2), int64(5), str(13)
memory usage: 1.0 MB

In [37]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
df.describe(include='all')

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
count,6607.000000,6607.000000,6607,6607,6607,6594.000000,6607.000000,6607,6607,6604.00000,6607,6529,6607,6607,6607.000000,6607,6517,6540,6607,6607.000000
unique,NaN,NaN,3,3,2,NaN,NaN,3,2,NaN,3,3,2,3,NaN,2,3,3,2,NaN
top,NaN,NaN,Medium,Medium,Yes,NaN,NaN,Medium,Yes,NaN,Low,Medium,Public,Positive,NaN,No,High School,Near,Male,NaN
freq,NaN,NaN,3362,3319,3938,NaN,NaN,3351,6108,NaN,2672,3925,4598,2638,NaN,5912,3223,3884,3814,NaN
mean,19.975329,79.977448,NaN,NaN,NaN,7.029421,75.070985,NaN,NaN,1.49364,NaN,NaN,NaN,NaN,2.967610,NaN,NaN,NaN,NaN,67.235659
std,5.990594,11.547475,NaN,NaN,NaN,1.468528,14.400397,NaN,NaN,1.23068,NaN,NaN,NaN,NaN,1.031231,NaN,NaN,NaN,NaN,3.890456
min,1.000000,60.000000,NaN,NaN,NaN,4.000000,50.000000,NaN,NaN,0.00000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,55.000000
25%,16.000000,70.000000,NaN,NaN,NaN,6.000000,63.000000,NaN,NaN,1.00000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,65.000000
50%,20.000000,80.000000,NaN,NaN,NaN,7.000000,75.000000,NaN,NaN,1.00000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,67.000000
75%,24.000000,90.000000,NaN,NaN,NaN,8.000000,88.000000,NaN,NaN,2.00000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,69.000000
max,44.000000,100.000000,NaN,NaN,NaN,10.000000,100.000000,NaN,NaN,8.00000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,101.000000

In [39]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
df.duplicated().sum()

np.int64(0)

In [37]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
df.columns
df.rename(columns={'Hours_Studied':'cybrom','Sleep_Hours':'hello'}) 
print(df.rename(index={0:'A'}))

      Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
A                23          84                  Low                High
1                19          64                  Low              Medium
2                24          98               Medium              Medium
3                29          89                  Low              Medium
4                19          92               Medium              Medium
...             ...         ...                  ...                 ...
6602             25          69                 High              Medium
6603             23          76                 High              Medium
6604             20          90               Medium                 Low
6605             10          86                 High                High
6606             15          67               Medium                 Low

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
A                            No          7.0               79
1                            No          8.0               56
2                           Yes          7.0               91
3                           Yes          8.0               98
4                           Yes          6.0               65
...                         ...          ...              ...
6602                         No          7.0               76
6603                         No          NaN               81
6604                        Yes          6.0               65
6605                        Yes          6.0               91
6606                        Yes          9.0               94

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
A                 Low             Yes                0.0           Low
1                 Low             Yes                2.0        Medium
2              Medium             Yes                2.0        Medium
3              Medium             Yes                1.0        Medium
4              Medium             Yes                3.0        Medium
...               ...             ...                ...           ...
6602           Medium             Yes                1.0          High
6603           Medium             Yes                3.0           Low
6604              Low             Yes                3.0           Low
6605             High             Yes                2.0           Low
6606           Medium             Yes                0.0        Medium

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
A             Medium      Public       Positive                  3
1             Medium      Public       Negative                  4
2             Medium      Public        Neutral                  4
3             Medium      Public       Negative                  4
4               High      Public        Neutral                  4
...              ...         ...            ...                ...
6602          Medium      Public       Positive                  2
6603            High      Public       Positive                  2
6604          Medium      Public       Negative                  2
6605          Medium     Private       Positive                  3
6606          Medium      Public       Positive                  4

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
A                       No              High School               Near
1                       No                  College           Moderate
2                       No             Postgraduate               Near
3                       No              High School           Moderate
4                       No                  College               Near
...                    ...                      ...                ...
6602                    No              High School               Near
6603                    No              High School               Near
6604                    No             Postgraduate               Near
6605                    No              High School                Far
6606                    No             Postgraduate               Near

      Gender  Exam_Score
A       Male          67
1     Female          61
2       Male          74
3       Male          71
4     Female          70
...      ...         ...
6602  Female          68
6603  Female          69
6604  Female          68
6605  Female          68
6606    Male          64

[6607 rows x 20 columns]

In [46]:
# inplace permanent rename krta hai

In [45]:
d = pd.read_excel('StudentPerformanceFactors.xlsx') 
df = pd.DataFrame(d) 
df.columns
df.rename(columns={'Hours_Studied':'cybrom','Sleep_Hours':'hello'},inplace=True)
print(df)

      cybrom  Attendance Parental_Involvement Access_to_Resources  \
0         23          84                  Low                High
1         19          64                  Low              Medium
2         24          98               Medium              Medium
3         29          89                  Low              Medium
4         19          92               Medium              Medium
...      ...         ...                  ...                 ...
6602      25          69                 High              Medium
6603      23          76                 High              Medium
6604      20          90               Medium                 Low
6605      10          86                 High                High
6606      15          67               Medium                 Low

     Extracurricular_Activities  hello  Previous_Scores Motivation_Level  \
0                            No    7.0               79              Low
1                            No    8.0               56              Low
2                           Yes    7.0               91           Medium
3                           Yes    8.0               98           Medium
4                           Yes    6.0               65           Medium
...                         ...    ...              ...              ...
6602                         No    7.0               76           Medium
6603                         No    NaN               81           Medium
6604                        Yes    6.0               65              Low
6605                        Yes    6.0               91             High
6606                        Yes    9.0               94           Medium

     Internet_Access  Tutoring_Sessions Family_Income Teacher_Quality  \
0                Yes                0.0           Low          Medium
1                Yes                2.0        Medium          Medium
2                Yes                2.0        Medium          Medium
3                Yes                1.0        Medium          Medium
4                Yes                3.0        Medium            High
...              ...                ...           ...             ...
6602             Yes                1.0          High          Medium
6603             Yes                3.0           Low            High
6604             Yes                3.0           Low          Medium
6605             Yes                2.0           Low          Medium
6606             Yes                0.0        Medium          Medium

     School_Type Peer_Influence  Physical_Activity Learning_Disabilities  \
0         Public       Positive                  3                    No
1         Public       Negative                  4                    No
2         Public        Neutral                  4                    No
3         Public       Negative                  4                    No
4         Public        Neutral                  4                    No
...          ...            ...                ...                   ...
6602      Public       Positive                  2                    No
6603      Public       Positive                  2                    No
6604      Public       Negative                  2                    No
6605     Private       Positive                  3                    No
6606      Public       Positive                  4                    No

     Parental_Education_Level Distance_from_Home  Gender  Exam_Score
0                 High School               Near    Male          67
1                     College           Moderate  Female          61
2                Postgraduate               Near    Male          74
3                 High School           Moderate    Male          71
4                     College               Near  Female          70
...                       ...                ...     ...         ...
6602              High School               Near  Female          68
6603              High School               Near  Female          69
6604             Postgraduate               Near  Female          68
6605              High School                Far  Female          68
6606             Postgraduate               Near    Male          64

[6607 rows x 20 columns]

In [25]:
s = [[1,2,3,4,5,6,7],[10,20,30,40,50,60,70],[100,200,300,400,500,600,700],[2,4,6,8,10,12,14],['a','b','c','d','e','f'],[12,34,56,78,]]
df = pd.DataFrame(s,columns=['m','t','w','th','fri','sat','sun']) 
#print(df)
print(df.head(2)) 
print(df.tail(4)) 
print(df.sample(3))
print(df.info())
print(df.describe(include='all'))

print(df.isnull())

    m   t   w  th fri sat   sun
0   1   2   3   4   5   6   7.0
1  10  20  30  40  50  60  70.0
     m    t    w   th   fri   sat    sun
2  100  200  300  400   500   600  700.0
3    2    4    6    8    10    12   14.0
4    a    b    c    d     e     f    NaN
5   12   34   56   78  None  None    NaN
     m    t    w   th  fri  sat    sun
2  100  200  300  400  500  600  700.0
3    2    4    6    8   10   12   14.0
0    1    2    3    4    5    6    7.0
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   m       6 non-null      object
 1   t       6 non-null      object
 2   w       6 non-null      object
 3   th      6 non-null      object
 4   fri     5 non-null      object
 5   sat     5 non-null      object
 6   sun     4 non-null      float64
dtypes: float64(1), object(6)
memory usage: 468.0+ bytes
None
          m    t    w   th  fri  sat         sun
count   6.0  6.0  6.0  6.0  5.0  5.0    4.000000
unique  6.0  6.0  6.0  6.0  5.0  5.0         NaN
top     1.0  2.0  3.0  4.0  5.0  6.0         NaN
freq    1.0  1.0  1.0  1.0  1.0  1.0         NaN
mean    NaN  NaN  NaN  NaN  NaN  NaN  197.750000
std     NaN  NaN  NaN  NaN  NaN  NaN  336.018229
min     NaN  NaN  NaN  NaN  NaN  NaN    7.000000
25%     NaN  NaN  NaN  NaN  NaN  NaN   12.250000
50%     NaN  NaN  NaN  NaN  NaN  NaN   42.000000
75%     NaN  NaN  NaN  NaN  NaN  NaN  227.500000
max     NaN  NaN  NaN  NaN  NaN  NaN  700.000000
       m      t      w     th    fri    sat    sun
0  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False
4  False  False  False  False  False  False   True
5  False  False  False  False   True   True   True