In [1]:
import pandas as pd 
import numpy as np

In [7]:
df = pd.read_csv('myrgroup.csv') 
print(df.isnull().sum())
print(df)
print(df.dropna())

day          0
city         0
weather      0
temp         1
windspeed    1
dtype: int64
        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN
        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0

In [12]:
A = [[1,2,3,np.nan],[np.nan,np.nan,np.nan , np.nan],[10,20,30,40]] 
df1 = pd.DataFrame(A) 
df1.dropna(how= 'all')  ## drop whole row

      0     1     2     3
0   1.0   2.0   3.0   NaN
2  10.0  20.0  30.0  40.0

In [20]:
A = [[1,2,3],[4,5,6,7,7],[2,3,4,5]] 
df = pd.DataFrame(A) 
df
df.fillna(2)  ## replace none values

   0  1  2    3    4
0  1  2  3  2.0  2.0
1  4  5  6  7.0  7.0
2  2  3  4  5.0  2.0

In [51]:
# fillna : used to fill a value in every none value in dataframe

A = [[1,2,3,4,5],[6,7,8,9,0],[None,None,None,None,None]]
a = pd.DataFrame(A, columns=['s1','s2','s3','s4','s5'])
# a.fillna(0)         default filling
print(a['s3'].fillna(5))     # filling at a specific position
# a['s3'] = a['s3'].fillna(5)    for permanent change
print(a)
print(a['s4'].fillna(a['s4'].mean()))    # replacing with mean value
a['s5'].ffill() 

# ffill fill  forword 
# bfill backword fill

0    3.0
1    8.0
2    5.0
Name: s3, dtype: float64
    s1   s2   s3   s4   s5
0  1.0  2.0  3.0  4.0  5.0
1  6.0  7.0  8.0  9.0  0.0
2  NaN  NaN  NaN  NaN  NaN
0    4.0
1    9.0
2    6.5
Name: s4, dtype: float64

0    5.0
1    0.0
2    0.0
Name: s5, dtype: float64

In [55]:
A = [[1,2,3],[4,5,6,7],[2,3,4,5]] 
df = pd.DataFrame(A)
print(df)

   0  1  2    3
0  1  2  3  NaN
1  4  5  6  7.0
2  2  3  4  5.0