In [1]:
import pandas as pd 
import numpy as np

In [3]:
l = [1,2,3,4,5,6,7] 
df = pd.DataFrame(l) 
df

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [4]:
l = [[1,2,3,4,5],[10,20,30,40,50,60]] 
df = pd.DataFrame(l) 
df

    0   1   2   3   4     5
0   1   2   3   4   5   NaN
1  10  20  30  40  50  60.0

In [6]:
l = [[1,2,3,4,5],[10,20,30,40,50,60]] 
df = pd.DataFrame(l,columns=['mon','tue','wed','thur','fri','sat']) 
df

   mon  tue  wed  thur  fri   sat
0    1    2    3     4    5   NaN
1   10   20   30    40   50  60.0

In [7]:
t = (1,2,3,4,5) 
df = pd.DataFrame(t) 
df

   0
0  1
1  2
2  3
3  4
4  5

In [12]:
d = {'x':[1],'y':[2],'z':[3]} 
print(type(d))
df = pd.DataFrame(d)
df

<class 'dict'>

   x  y  z
0  1  2  3