In [1]:
import pandas as pd 
import numpy as np

In [5]:
## for even columns: 

df1 = pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]}) 
df2 = pd.DataFrame({"C":[10,20,30,40],"D":[50,60,70,80]}) 
print(df1) 
print(df2)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8
    C   D
0  10  50
1  20  60
2  30  70
3  40  80

In [8]:
df1.join (df2) ## join two table

   A  B   C   D
0  1  5  10  50
1  2  6  20  60
2  3  7  30  70
3  4  8  40  80

In [12]:
# for uneven columns : it fills nan 

df1 = pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]}) 
df2 = pd.DataFrame({"C":[10,20],"D":[50,60]}) 
df1.join (df2)

   A  B     C     D
0  1  5  10.0  50.0
1  2  6  20.0  60.0
2  3  7   NaN   NaN
3  4  8   NaN   NaN

In [14]:
# for uneven columns: assigning index for uneven columns : it wont disply  the ddata of less 
df1 = pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]},index=['a','b','c','d']) 
df2 = pd.DataFrame({"C":[10,20],"D":[50,60]}) 
df1.join(df2) ## priority with left dataframe

   A  B   C   D
a  1  5 NaN NaN
b  2  6 NaN NaN
c  3  7 NaN NaN
d  4  8 NaN NaN

In [21]:
df1 = pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]},index=['a','b','c','d']) 
df2 = pd.DataFrame({"C":[10,20],"D":[50,60]},index= ['c','d'])  
df1.join(df2)

   A  B     C     D
a  1  5   NaN   NaN
b  2  6   NaN   NaN
c  3  7  10.0  50.0
d  4  8  20.0  60.0

In [25]:
df1 = pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]}) 
df2 = pd.DataFrame({"C":[10,20,30,40],"D":[50,60,70,80]},index= ['a','b','c','d'])   
df2.join(df1)

    C   D   A   B
a  10  50 NaN NaN
b  20  60 NaN NaN
c  30  70 NaN NaN
d  40  80 NaN NaN

In [29]:
df3 = pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]},index=['a','b','c','d']) 
df4 = pd.DataFrame({"C":[10,20,30,40],"D":[50,60,70,80]},index= ['a','b','x','d'])   
df1.join(df2)  
print("inner join",df3.join(df4,how="inner")) 
print("left join",df3.join(df4,how="left"))
print("right join",df3.join(df4,how="right"))

inner join    A  B   C   D
a  1  5  10  50
b  2  6  20  60
d  4  8  40  80
left join    A  B     C     D
a  1  5  10.0  50.0
b  2  6  20.0  60.0
c  3  7   NaN   NaN
d  4  8  40.0  80.0
right join      A    B   C   D
a  1.0  5.0  10  50
b  2.0  6.0  20  60
x  NaN  NaN  30  70
d  4.0  8.0  40  80