In [2]:
import pandas as pd 
import numpy as np

In [3]:
data = pd.read_csv("pandas_csv.csv") 
data

      Name  Age  Gender  Marks
0     Amit   20    Male     85
1     Neha   21  Female     90
2    Rahul   19    Male     70
3    Priya   22  Female     65
4    Karan   20    Male     88
5    Sneha   21  Female     92
6    Vikas   23    Male     60
7   Anjali   20  Female     75
8    Rohit   22    Male     80
9    Pooja   19  Female     89
10   Arjun   21    Male     55
11   Kavya   20  Female     77
12  Manish   23    Male     66
13   Divya   22  Female     72
14  Suresh   21    Male     95

In [4]:
# Q.2 Display top 3 rows 
print(data.head(3))

    Name  Age  Gender  Marks
0   Amit   20    Male     85
1   Neha   21  Female     90
2  Rahul   19    Male     70

In [5]:
#Q.3 Display last 3 rows 
print(data.tail(3))

      Name  Age  Gender  Marks
12  Manish   23    Male     66
13   Divya   22  Female     72
14  Suresh   21    Male     95

In [8]:
#Q.4 Find number of rows and number of columns 
print(data.shape)

(15, 4)

In [10]:
#Q.5 Get information like total number of rows,total number of columns,data types of each column
#and memory requirement 
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    15 non-null     str
 1   Age     15 non-null     int64
 2   Gender  15 non-null     str
 3   Marks   15 non-null     int64
dtypes: int64(2), str(2)
memory usage: 612.0 bytes
None

In [11]:
#Q.6 Check null values in the dataset
print(data.isnull().sum())

Name      0
Age       0
Gender    0
Marks     0
dtype: int64

In [12]:
#Q.7 Get overall statistics about the dataframe 
print(data.describe())

             Age      Marks
count  15.000000  15.000000
mean   20.933333  77.266667
std     1.279881  12.452577
min    19.000000  55.000000
25%    20.000000  68.000000
50%    21.000000  77.000000
75%    22.000000  88.500000
max    23.000000  95.000000

In [22]:
#Q.8 Find unique values from the gender column 
df = data.groupby("Gender")
for k in df:
    print(k)

('Female',       Name  Age  Gender  Marks
1     Neha   21  Female     90
3    Priya   22  Female     65
5    Sneha   21  Female     92
7   Anjali   20  Female     75
9    Pooja   19  Female     89
11   Kavya   20  Female     77
13   Divya   22  Female     72)
('Male',       Name  Age Gender  Marks
0     Amit   20   Male     85
2    Rahul   19   Male     70
4    Karan   20   Male     88
6    Vikas   23   Male     60
8    Rohit   22   Male     80
10   Arjun   21   Male     55
12  Manish   23   Male     66
14  Suresh   21   Male     95)

In [23]:
#Q.11 Find the total number of students having marks between 70 to 90(inclusive) using between
data[data["Marks"].between(70,90)]

      Name  Age  Gender  Marks
0     Amit   20    Male     85
1     Neha   21  Female     90
2    Rahul   19    Male     70
4    Karan   20    Male     88
7   Anjali   20  Female     75
8    Rohit   22    Male     80
9    Pooja   19  Female     89
11   Kavya   20  Female     77
13   Divya   22  Female     72

In [25]:
#Q.12 Find average marks.
print(data['Marks'].mean())

77.26666666666667

In [26]:
#Q.13 using apply method get increment the marks of each student by 5
print(data["Marks"].apply(lambda x:x+5))

0      90
1      95
2      75
3      70
4      93
5      97
6      65
7      80
8      85
9      94
10     60
11     82
12     71
13     77
14    100
Name: Marks, dtype: int64

In [31]:
#Q.14 Count the length of student name.

15